ministack/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from preguntas import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^preguntas/', include('preguntas.urls')),
    url(r'^login/$',  views.the_login, name='the_login'),
    url(r'^logout/$',  views.the_logout, name='the_logout'),
]

preguntas/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$',  views.index, name='index'),
    url(r'^categoria/(?P<categoria_id>.*)$',  views.categoria, name='categoria'),
    url(r'^crear$',  views.crear_pregunta, name='crear_pregunta'),
    url(r'^pregunta/(?P<pregunta_id>.*)$',  views.pregunta, name='pregunta'),
    
]

preguntas/models.py
from __future__ import unicode_literals

from django.db import models

class Categoria(models.Model):
    nombre = models.CharField(max_length=255)

    def __unicode__(self):
        return self.nombre

class Pregunta(models.Model):
    titulo = models.CharField(max_length=255)
    descripcion = models.TextField()
    fecha = models.DateTimeField()
    categoria = models.ManyToManyField(Categoria)

    def __unicode__(self):
        return self.titulo

class Comentario(models.Model):
  contenido = models.TextField()
  pertenece_a = models.ForeignKey(Pregunta, default = None)

preguntas/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm, TextInput, Textarea, SelectMultiple, HiddenInput

from .models import Pregunta, Comentario

class PreguntaForm(ModelForm):
  class Meta:
    model = Pregunta
    fields = ['titulo', 'descripcion', 'categoria']

    widgets = {
      'titulo': TextInput(attrs = {
        'class': 'form-control',
        'placeholder': 'Título',
        'required': 'required'
      }),
      'descripcion': Textarea(attrs = {
        'class': 'form-control',
        'placeholder': 'Descripción',
        'required': 'required'
      }),
      'categoria': SelectMultiple(attrs = {
        'class': 'form-control',
        'required': 'required',
      }),
    }

class ComentarioForm(ModelForm):
  class Meta:
    model = Comentario
    fields = ['contenido']

    widgets = {
      'contenido': Textarea(attrs = {
        'class': 'form-control',
        'placeholder': 'Agregue su comentario aquí',
        'required': 'required'
      }),
    }

preguntas/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

from .models import Categoria, Pregunta, Comentario

from .forms import PreguntaForm, ComentarioForm

def index(request):
    preguntas = Pregunta.objects.all()
    context = {'preguntas': preguntas}
    return render(request, 'index.html', context)

def categoria(request, categoria_id):
    try:
        categoria = Categoria.objects.get(pk = categoria_id)
    except Categoria.DoesNotExist:
        raise Http404
    context = {'categoria': categoria}
    return render(request, 'categoria.html', context)

def crear_pregunta_hastalas(request):
    if request.method == 'POST':
        from django.utils import timezone
        titulo = request.POST.get('titulo')
        descripcion = request.POST.get('descripcion')
        _categorias = request.POST.getlist('categoria[]')
        fecha = timezone.now()

        pregunta = Pregunta(titulo = titulo, descripcion = descripcion, fecha = fecha)
        pregunta.save()

        for cat in _categorias:
            categoria = Categoria.objects.get(pk = cat)
            pregunta.categoria.add(categoria)

        pregunta.save()

        messages.success(request, 'Se ha creado una nueva pregunta')

    categorias = Categoria.objects.all()
    context = {'categorias': categorias}
    return render(request, 'crear.html', context)

@login_required
def crear_pregunta(request):
    form = PreguntaForm()
    if request.method == 'POST':
        form = PreguntaForm(request.POST)

        if form.is_valid():
            pregunta = form.save(commit = False)
            from django.utils import timezone
            pregunta.fecha = timezone.now()
            pregunta.save()
            form.save_m2m()
            messages.success(request, 'Se ha creado una nueva pregunta.')
        else:
            messages.error(request, 'No se pudo guardar, intente nuevamente.')

    categorias = Categoria.objects.all()
    context = {'categorias': categorias, 'form': form}
    return render(request, 'crear.html', context)

def pregunta(request, pregunta_id):
    form = ComentarioForm()
    if request.method == 'POST':
        form = ComentarioForm(request.POST)
        if form.is_valid():
            comentario = form.save(commit = False)
            comentario.pertenece_a = Pregunta.objects.get(pk = pregunta_id)
            comentario.save()

            messages.success(request, 'Se ha añadido el comentario.')

            form = ComentarioForm()

        else:
            messages.error(request, 'No se pudo guardar, intente nuevamente.')


    try:
        pregunta = Pregunta.objects.get(pk = pregunta_id)
    except Pregunta.DoesNotExist:
        raise Http404
    context = {'pregunta': pregunta, 'form': form}
    return render(request, 'pregunta.html', context)


def the_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username, password = password)
        print user
        if user is not None:
            login(request, user)
            if request.POST.get('next') is not None:
                return HttpResponseRedirect(request.POST.get('next'))
            else:
                return HttpResponseRedirect(reverse('index'))
            messages.error(request, 'Bienvenido.')
        else:
            messages.error(request, 'Revise el usuario o la contraseña.')

    next = request.GET.get('next')
    context = {'next': next}
    return render(request, 'login.html', context)


def the_logout(request):
    messages.success(request, 'Hasta pronto')
    logout(request)

    return HttpResponseRedirect(reverse('index'))

preguntas/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title%}Titulo{% endblock %}</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/css.css' %}">
</head>
<body>
  <header>
      <nav>
        <ul class="nav nav-pills">
          <li><a href="{% url 'index' %}">Home</a></li>
          <li><a href="{% url 'crear_pregunta' %}">Crear pregunta</a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'the_logout' %}">Salir</a></li>
          {% endif %}
        </ul>
      </nav>
    </header>
  <div class="container">
    <div class="row">
      {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
          <p>{{message}}</p>
        </div>
        {% endfor %}
      {% endif %}
      <div class="col-md-8">
        <div class="content">
          {% block content %}{% endblock %}
        </div>
      </div>
      <div class="col-md-4">
        <div class="sidebar">
          {% block sidebar %}{% endblock %}          
        </div>
      </div>
    </div>
  </div>
</body>
</html>

preguntas/templates/categoria.html
{% extends 'base.html' %}

{% block content %}
<div class="page-header">
  <h1>Preguntas bajo la categoría <span class="label label-info"></span>"{{ categoria.nombre }}"</h1>
  {% for pregunta in categoria.pregunta_set.all %}
    <article>
      <h3><a href="{% url 'pregunta' pregunta.pk %}">{{ pregunta.titulo }}</a></h3>
      <p>{{ pregunta.descripcion }}</p>
      <div class="categorias">
        <ul class="list-inline">
          {% for categoria in pregunta.categoria.all %}
            <li><a href="{% url 'categoria' categoria.pk %}" class="btn btn-xs btn-info">{{ categoria.nombre }}</a></li>
          {% endfor %}
        </ul>
      </div>
    </article>
  {% endfor %}
</div>
{% endblock %}

{% block sidebar %}

{% endblock %}

preguntas/templates/crear.html
{% extends 'base.html' %}

{% block content %}
<div class="page-header">
  <h1>Crear pregunta</h1>
</div>

<form action="{% url 'crear_pregunta' %}" method="post">
  {% for error in form.errors %}
  <div class="alert alert-danger">
    {{ error }}
  </div>
  {% endfor %}
  <div class="form-group">
    <label for="">{{ form.titulo.label }}</label>
    {{ form.titulo }}
  </div>
  <div class="form-group">
    {{ form.descripcion }}
  </div>
  <div class="form-group">
    {{ form.categoria }}
  </div>
  <div class="well">
    <button class="btn btn-lg btn-block btn-primary" type="submit">Guardar</button>
  </div>
  {% csrf_token %}
</form>
{% endblock%}

preguntas/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="page-header">
  <h1>Preguntas</h1>
  {% for pregunta in preguntas %}
    <article>
      <h3><a href="{% url 'pregunta' pregunta.pk %}">{{ pregunta.titulo }}</a></h3>
      <p>{{ pregunta.descripcion }}</p>
      <div class="categorias">
        <ul class="list-inline">
          {% for categoria in pregunta.categoria.all %}
            <li><a href="{% url 'categoria' categoria.pk %}" class="btn btn-xs btn-info">{{ categoria.nombre }}</a></li>
          {% endfor %}
        </ul>
      </div>
    </article>
  {% endfor %}
</div>
{% endblock %}

{% block sidebar %}

{% endblock %}

preguntas/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="page-header">
  <h1>Login</h1>
</div>

<form class="form" method="POST" action="{% url 'the_login' %}">
  <div class="form-group">
    <input type="text" class="form-control" name="username" placeholder="Usuario" required>
  </div>
  <div class="form-group">
    <input type="password" class="form-control" name="password" placeholder="Password" required>
  </div>
  {% csrf_token %}
  {% if next %}
  <input type="hidden" name="next" value="{{ next }}">
  {% endif %}
  <div class="well">
  <button class="btn btn-primary btn-block" type="submit">Ingresar</button>
  </div>
</form>
{% endblock %}

{% block sidebar %}

{% endblock %}

preguntas/templates/pregunta.html
{% extends 'base.html' %}

{% block content %}
<div class="page-header">
  <h1>{{ pregunta.titulo}}</h1>
</div>

<p>{{ pregunta.descripcion }}</p>
<hr>
<div class="categorias">
  <ul class="list-inline">
    {% for categoria in pregunta.categoria.all %}
      <li><a href="{% url 'categoria' categoria.pk %}" class="btn btn-xs btn-info">{{ categoria.nombre }}</a></li>
    {% endfor %}
  </ul>
</div>

<hr>

<div class="page-header">
  <h2>Comentarios</h2>
</div>

  <ol>
    {% for comentario in pregunta.comentario_set.all %}
    <li name="{{ comentario.pk }}">
      {{ comentario.contenido }} (<a href="#{{ comentario.pk }}">#</a>)
    </li>
    {% empty %}
    <li>No existe ningún comentario. <a href="#comentario-form">Agregar Comentario</a></li>
    {% endfor %}
  </ol>

<hr>
<div class="page-header">
  <h2>Agregar Comentario</h2>
</div>

<div id="comentario-form">
  <form action="{% url 'pregunta' pregunta.pk %}" method="post">
    <div class="form-group">
      {{ form.contenido }}
    </div>
    {% csrf_token %}
    <div class="well">
      <button class="btn btn-block btn-primary" type="submit">Agregar comentario</button>
    </div>
  </form>
</div>

{% endblock %}

{% block title %}Pregunta: {{ pregunta.titulo }}{% endblock %}